<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_guard_remember_key' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Wed Jul 23 03:30:59 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfGuardPlugin.lib.model
 */
class sfGuardRememberKeyQuery extends BasesfGuardRememberKeyQuery
{
}
